services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    image: workspace
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
      - 35729:35729 # docusaurus
    volumes:
      - ../../:/workspace